# Generated by Django 4.0.4 on 2022-05-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0002_auto_20220529_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userofapp',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
