# Generated by Django 4.0.4 on 2022-05-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0005_alter_userofapp_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userofapp',
            name='photo',
            field=models.CharField(default='face_db/12selfie.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='userofapp',
            name='temperature_preference',
            field=models.CharField(default='24', max_length=500),
        ),
    ]
