# Generated by Django 4.0.4 on 2022-05-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0006_alter_userofapp_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userofapp',
            name='photo',
            field=models.CharField(default='face_db/9Aditya_Chavan_Photo.jpg', max_length=500),
        ),
    ]
